# Generated by Django 5.1.5 on 2025-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
